services:
  - type: web
    name: crystaland-pdf-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd pdf-generators && gunicorn app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: AC_API_URL
        value: https://crystaland.api-us1.com
      - key: AC_API_KEY
        sync: false
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: "587"
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: SENDER_NAME
        value: Crystaland
